language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
